import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import * as React from "react";
import styles from "../styles/Home.module.css";

interface TextAreaProps {
  onEnter: () => void;
  onChange: React.ChangeEventHandler<HTMLTextAreaElement>;
  text: string;
}

const TextArea: React.VFC<TextAreaProps> = ({ onEnter, text, onChange }) => {
  const handleKeyDown: React.KeyboardEventHandler<HTMLTextAreaElement> = (
    event
  ) => {
    if (event.metaKey && event.key === "Enter") {
      onEnter();
    }
  };

  return (
    <textarea
      style={{ width: `600px`, height: `600px` }}
      value={text}
      onChange={onChange}
      onKeyDown={handleKeyDown}
    />
  );
};

const Home: NextPage = () => {
  const [count, setCount] = React.useState(0);
  const [participants, setParticipants] = React.useState(["A", "B"]);
  const [text, setText] = React.useState("");

  const onEnter = () => {
    const order = count % 2;

    if (order === 0) {
      setText((text) => text + "\n" + participants[0] + ": ");
    } else {
      setText((text) => text + "\n" + participants[1] + ": ");
    }

    setCount((count) => count + 1);
  };

  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setText((text) => event.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>{`${participants[0]}と${participants[1]}さんの対談`}</h3>
        <TextArea text={text} onEnter={onEnter} onChange={handleChange} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
